[answers]
says_what = "Classy, sophisticated, timeless"
never_look_like = "a slob"
three_words = "sharp, coherent, classic"
audience = "my girlfriend"
vibes_love = "60s Milanese"
icons = "Richard Gere in American gigolo"
stolen_outfit = "richard gere tobacco suit"
world = "italy"
try_hard = "crocs"
