[answers]
says_what = "This guy is varied. i dont being labelled. not in a box but appropriate for the context."
never_look_like = "Dont want my casual look to look like my streetwear."
three_words = "sexy, memorable, happy"
audience = "My partner"
vibes_love = "relaxed surfer vibe, skaters"
icons = "luke evans style, austin butler, lenny kravitz, tom hiddleston"
stolen_outfit = "A guy who is dressed formally,"
world = "city: Valencia today.  late 70s, early 80s American."
try_hard = "simple hoodies, black north face puffer, branded gorpcore"
wrong_signal = "tea towel looking primark overshirt"
missing = "smart trousers"
actually_wear = "Dickies trouser"
never_worn = "leather motorcycle jacket"
default_outfit = "navy parachute trousers, white t shirt, black leather jacket"
felt_great = "sleevless denim jacket, grey tie die t shirt, black technical hiking trousers"
keepers = "skip, too many to say. but maybe black leather jacket"
fit_preference = "regular fit trousers, jackets are a little bit oversize, no longer than the hip area."
flatter = "Accentuate V taper"
fit_problems = "no issues"
palette_width = "raaaange for sure"
fabrics = "love: curdoroy, leather\nhate: polyester"
priorities = "Practicality 3, Comfort 4, Aesthetics 6, Cost 7"
upkeep = "ironing clothes that are smart and need ironing. hand washing is fine, etc."
normal_week = "capoeira, climbing, commuting on train, going to tesco, going on dates, going dancing, going to festivals"
